build_project.py: get_git_commit_id: fix missing error reporting
Currently if get_git_commit_id() fails, its not clear why:

  Generation for Bootloader to /build_dir has completed.
    ...snip...
     File "/usr/lib/python3.11/subprocess.py", line 571, in run
       raise CalledProcessError(retcode, process.args,
   subprocess.CalledProcessError: Command '['git', '-C', '/build', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

So lets fix it by providing stderr output, thus making the issue
obvious:

  Generation for Bootloader to /build_dir has completed.
    ...snip...
    File "/build/tools/build_project.py", line 113, in git
      raise RuntimeError(
      RuntimeError: Git command `git -C /build rev-parse HEAD` failed: fatal: detected dubious ownership in repository at '/build'
      To add an exception for this directory, call:

          git config --global --add safe.directory /build

Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>